on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'website/**'

permissions:
  contents: write

jobs:
  build-gem:
    if: github.repository == 'hashicorp/vagrant'
    name: Build Vagrant RubyGem
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@31a7f6d628878b80bc63375a93ae079ec50a1601 # v1.143.0
        with:
          ruby-version: '3.1'
      - name: Setup Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - name: Build RubyGem and binary
        run: ./.ci/build.sh
        working-directory: ${{github.workspace}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
