on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'builtin/**'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows**'
      - 'go.mod'
      - 'go.sum'
  # Allows manual trigger on arbitrary branches via GitHub UI/API
  workflow_dispatch:

jobs:
  vagrant-spec-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['^1.16']
        ruby: ['3.1']
    name: Vagrant acceptance tests
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: 'recursive'
          # Also fetch all tags, since we need our version number in the build
          # to be based off a tag
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: ${{matrix.go}}
      - name: Setup Ruby
        uses: ruby/setup-ruby@31a7f6d628878b80bc63375a93ae079ec50a1601 # v1.143.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Build Vagrant
        run:  |
          git config --global url."https://${HASHIBOT_USERNAME}:${HASHIBOT_TOKEN}@github.com".insteadOf "https://github.com"
          make bin/linux
        env:
          HASHIBOT_USERNAME: ${{ secrets.HASHIBOT_USERNAME }}
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
      - name: Add binstubs to path
        run: |
          echo "$PWD/binstubs" >> $GITHUB_PATH
        env:
          VAGRANT_SPEC_BOX: "hashicorp/bionic64"
      - name: Run vagrant-spec
        run: |
          VAGRANT_PATH="$GITHUB_WORKSPACE/vagrant" bundle exec vagrant-spec test --components=cli/version --config test/vagrant-spec/configs/vagrant-spec.config.virtualbox.rb
        env:
          VAGRANT_SPEC_BOX: "hashicorp/bionic64"
